# Numpy

## 1. array

In [1]:
import numpy as np

In [3]:
array_1 = np.array([[1.0, 2.0, 3], [4.0, 5, 6]])

In [4]:
array_1.shape # row, column size

(2, 3)

In [5]:
array_1.size # num of elements

6

In [6]:
array_1.dtype # array elements type

dtype('float64')

In [7]:
array_2 = np.arange(1, 10, 2)

In [8]:
array_2

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
array_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);

In [14]:
array_3[:2, 1:]

array([[2, 3],
       [5, 6]])

In [3]:
import numpy as np

In [4]:
np.random.randn(10)

array([ 0.90460399, -1.28421787, -0.35627385, -1.74633273, -1.0668621 ,
        0.19683418,  0.43289544, -0.60985525,  0.37466247,  1.07081154])

In [5]:
np.random.randint(10, size=(2, 3))

array([[7, 6, 9],
       [1, 0, 3]])

In [8]:
np.random.randint(10, size=20).reshape(4, 5)

array([[6, 4, 3, 6, 4],
       [4, 6, 1, 3, 9],
       [4, 2, 4, 1, 1],
       [6, 9, 7, 1, 0]])

In [10]:
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [11]:
array_1 = np.array([[1.0, 2.0, 3], [4.0, 5, 6]])

In [12]:
np.mat(array_1)

matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
np.random.randint(10, size=(2, 3))

array([[0, 1, 3],
       [9, 0, 4]])

In [14]:
a = np.random.randint(10, size=(2, 3))

In [15]:
np.unique(a)

array([0, 1, 3, 6, 8])

In [16]:
a

array([[0, 3, 6],
       [1, 8, 0]])

In [17]:
sum(a)

array([ 1, 11,  6])

In [18]:
sum(a[1:])

array([1, 8, 0])

In [19]:
sum(a[0])

9

In [20]:
sum(a[:0])

0

In [21]:
sum(a[:,0])

1

In [22]:
sum(a[:,1])

11

In [23]:
a.max()

8

In [25]:
max(a[0])

6

In [26]:
max(a[:,1])

8

In [40]:
x = np.arange(20)

In [31]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.save('one_array.npy', x)

In [39]:
!ls

numpy.ipynb   one_array.npy


In [42]:
np.load('one_array.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
y = np.load('one_array.npy')

In [37]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
np.savez('two_array.npz', a=x, b=y)

In [46]:
!ls

numpy.ipynb   one_array.npy two_array.npz


In [47]:
c= np.load('two_array.npz')

In [48]:
c

In [49]:
c['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
c.a

AttributeError: 'NpzFile' object has no attribute 'a'