# Numpy

## 1. array

In [1]:
import numpy as np

In [3]:
array_1 = np.array([[1.0, 2.0, 3], [4.0, 5, 6]])

In [4]:
array_1.shape # row, column size

(2, 3)

In [5]:
array_1.size # num of elements

6

In [6]:
array_1.dtype # array elements type

dtype('float64')

In [7]:
array_2 = np.arange(1, 10, 2)

In [8]:
array_2

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
array_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);

In [14]:
array_3[:2, 1:]

array([[2, 3],
       [5, 6]])