In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print(tf.__version__)

2.4.1


In [4]:
x = tf.constant([[1, 9], [3, 6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [5]:
x.numpy()

array([[1, 9],
       [3, 6]], dtype=int32)

In [8]:
x1 = np.ones([2, 2])
tf.multiply(x1, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>